apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f51bctvze-go
  janus-idp.io/tekton: f51bctvze-go
  backstage.io/kubernetes-id: f51bctvze-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f51bctvze-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
